#!/usr/bin/env python3
"""
OpenClaw Nightly Memory Review
Scans Discord channels + daily logs, extracts patterns/decisions, suggests MEMORY.md updates.
Runs via cron every night at 2am.
"""

import json
from pathlib import Path
from datetime import datetime, timedelta

WORKSPACE = Path(__file__).parent.parent
MEMORY_DIR = WORKSPACE / "memory"
KEYWORDS_FILE = MEMORY_DIR / "pattern-detection-keywords.json"
SUGGESTIONS_FILE = MEMORY_DIR / "suggested-updates.md"

def load_keywords():
    """Load pattern detection keywords."""
    with open(KEYWORDS_FILE) as f:
        return json.load(f)

def scan_daily_logs(days=1):
    """Scan recent daily logs for patterns."""
    findings = {
        'learnings': [],
        'patterns': [],
        'mistakes': [],
        'decisions': [],
        'axiomCandidates': []
    }
    
    # Get today's log
    today = datetime.now()
    log_file = MEMORY_DIR / f"{today.strftime('%Y-%m-%d')}.md"
    
    if not log_file.exists():
        return findings
    
    content = log_file.read_text()
    keywords = load_keywords()['keywords']
    
    # Scan for each keyword category
    for category, kw_list in keywords.items():
        for keyword in kw_list:
            if keyword.lower() in content.lower():
                # Extract context (line containing keyword + next line)
                for i, line in enumerate(content.split('\n')):
                    if keyword.lower() in line.lower():
                        context = line
                        if i < len(content.split('\n')) - 1:
                            context += ' ' + content.split('\n')[i+1]
                        findings[category].append({
                            'keyword': keyword,
                            'context': context.strip(),
                            'source': str(log_file.relative_to(WORKSPACE))
                        })
    
    return findings

def generate_suggestions(findings):
    """Generate suggested updates for MEMORY.md."""
    suggestions = []
    
    # Axiom candidates (found 3+ times or marked as rule/principle)
    if len(findings['axiomCandidates']) >= 3:
        suggestions.append({
            'type': 'new_axiom',
            'priority': 'high',
            'items': findings['axiomCandidates']
        })
    
    # Patterns
    if findings['patterns']:
        suggestions.append({
            'type': 'pattern',
            'priority': 'medium',
            'items': findings['patterns']
        })
    
    # Decisions
    if findings['decisions']:
        suggestions.append({
            'type': 'decision',
            'priority': 'high',
            'items': findings['decisions']
        })
    
    # Learnings
    if findings['learnings']:
        suggestions.append({
            'type': 'learning',
            'priority': 'medium',
            'items': findings['learnings']
        })
    
    # Mistakes
    if findings['mistakes']:
        suggestions.append({
            'type': 'mistake',
            'priority': 'low',
            'items': findings['mistakes']
        })
    
    return suggestions

def write_suggestions(suggestions):
    """Write suggestions to markdown file."""
    if not suggestions:
        SUGGESTIONS_FILE.write_text("# No suggestions found today.\n")
        return
    
    output = f"# Memory Update Suggestions ({datetime.now().strftime('%Y-%m-%d')})\n\n"
    output += "Generated by nightly memory review. Review and integrate during next heartbeat.\n\n"
    output += "---\n\n"
    
    for suggestion in suggestions:
        stype = suggestion['type']
        priority = suggestion['priority']
        items = suggestion['items']
        
        output += f"## {stype.replace('_', ' ').title()} (Priority: {priority})\n\n"
        
        for item in items:
            output += f"**Keyword:** {item['keyword']}  \n"
            output += f"**Context:** {item['context']}  \n"
            output += f"**Source:** {item['source']}  \n\n"
        
        output += "---\n\n"
    
    SUGGESTIONS_FILE.write_text(output)
    print(f"✓ Wrote {len(suggestions)} suggestion(s) to {SUGGESTIONS_FILE}")

def main():
    """Run nightly review."""
    print("OpenClaw Nightly Memory Review")
    print("=" * 50)
    print(f"Time: {datetime.now().isoformat()}")
    
    # Scan daily logs
    print("\nScanning daily logs...")
    findings = scan_daily_logs(days=1)
    
    total_findings = sum(len(v) for v in findings.values())
    print(f"  Found {total_findings} pattern matches")
    for category, items in findings.items():
        if items:
            print(f"    {category}: {len(items)}")
    
    # Generate suggestions
    print("\nGenerating suggestions...")
    suggestions = generate_suggestions(findings)
    print(f"  Generated {len(suggestions)} suggestion categories")
    
    # Write output
    print("\nWriting suggestions...")
    write_suggestions(suggestions)
    
    print("\n" + "=" * 50)
    print("✓ Nightly review complete")
    print(f"  Review suggestions: {SUGGESTIONS_FILE}")

if __name__ == '__main__':
    main()
