[env:esp32cam]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps =
    ESP32 Arduino Sketch Data Upload
    ArduinoWebsockets
    ArduinoJson
    https://github.com/esp32-camera-plus/esp32-camera

build_flags =
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_ESP32S3_CAM
    -DCORE_DEBUG_LEVEL=3

upload_speed = 921600
